# Generated by Django 2.0.4 on 2018-04-29 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_document_course_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fuckoff',
        ),
    ]
